version: '2'

services:
    swagger:
        build: ./docker/swagger
        ports:
            - 8001:8001
    php:
        build: ./docker/php
        working_dir: /var/www/application
        volumes:
            - ./application:/var/www/application
        container_name: php

    nginx:
        build: ./docker/nginx
        ports:
            - 80:80
        links:
            - php
        volumes:
            - ./application:/var/www/application
        container_name: nginx

    composer:
        image: composer/composer
        working_dir: /var/www/application
        volumes:
            - ./application:/var/www/application
        container_name: composer